title: Amit's Homepage
description: first try to the site world!
# Use local layouts/assets. GitHub Pages will build with Jekyll automatically for this repo.
author: Amit
# baseurl: "" # not needed for a user/organization site
# url: "https://amsharm2.github.io" # optional
